#!/usr/bin/env python3
"""Falsify candidate proof-tree provenance for long high returns.

This is a discovery tool, not a proof of the no-DRAW theorem.  It constructs
the exact arithmetic factor fork generated by an A-selecting obligation,
enumerates every long-tail route to an exponent-two/one boundary, and tests
whether the locally finite high-return states u,c occur below either of the
two actual children E,D of the retained LOSS witness V.
"""

from __future__ import annotations

import argparse
from collections import deque

from optimal_3n1.game import (
    constant_tail_coordinates,
    constant_tail_state,
    embedded_original_state,
    source_A_selecting_tail_bit,
    transformed_A,
    transformed_B,
    transformed_moves,
    v2,
)


def descendants(root: int, max_depth: int) -> dict[int, tuple[int, str]]:
    """Return the least directed distance and A/B word from root."""
    distance = {root: (0, "")}
    queue: deque[int] = deque([root])
    while queue:
        state = queue.popleft()
        depth, word = distance[state]
        if depth == max_depth or state == 0:
            continue
        for letter, child in zip("AB", transformed_moves(state)):
            if child not in distance:
                distance[child] = (depth + 1, word + letter)
                queue.append(child)
    return distance


def boundary_levels(lower_exponent: int) -> list[int]:
    """Powers of three reachable when a long adjacent tail hits 2/1."""
    frontier = {(lower_exponent, 0), (lower_exponent + 1, 0)}
    result: set[int] = set()
    while frontier:
        exponent, power = frontier.pop()
        if exponent <= 2:
            result.add(power)
            continue
        frontier.add((exponent - 1, power + 1))
        frontier.add((exponent - 2, power + 1))
    return sorted(result)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-limit", type=int, default=20_000)
    parser.add_argument("--depth", type=int, default=24)
    parser.add_argument("--examples", type=int, default=20)
    parser.add_argument("--show-hits", action="store_true")
    args = parser.parse_args()

    checked = 0
    misses: list[tuple[int, ...]] = []
    hits: list[tuple[int, ...]] = []

    for x in range(1, args.source_limit + 1):
        e = source_A_selecting_tail_bit(x)
        g = 1 - e
        coefficient = embedded_original_state(x)
        p = constant_tail_state(coefficient, 1, e)
        upper = constant_tail_state(coefficient, 2, e)
        V = transformed_A(p)
        b = transformed_B(p)
        F = transformed_A(upper)
        E = transformed_A(V)
        D = transformed_B(V)

        upper_factor = transformed_A(F)
        lower_factor = transformed_B(F)
        upper_a, upper_r, upper_g = constant_tail_coordinates(upper_factor)
        lower_a, lower_r, lower_g = constant_tail_coordinates(lower_factor)
        if not (
            upper_a == lower_a == embedded_original_state(b)
            and upper_r == lower_r + 1
            and upper_g == lower_g == g
        ):
            raise AssertionError((x, upper_factor, lower_factor))

        dist_e = descendants(E, args.depth)
        dist_d = descendants(D, args.depth)
        for k in boundary_levels(lower_r):
            a = (3**k) * embedded_original_state(b)
            numerator = 3 * a + 1 - 2 * g
            valuation = v2(numerator)
            if valuation < 7:
                continue
            returned_coefficient = numerator >> valuation
            # The high-return notation uses returned_coefficient=J(t).
            # Its exact source is not needed for the state identities.
            u = constant_tail_state(returned_coefficient, valuation - 1, 1 - g)
            c = constant_tail_state(3 * returned_coefficient, valuation - 3, 1 - g)
            checked += 1
            row = (
                x,
                lower_r,
                k,
                valuation,
                V,
                E,
                D,
                u,
                c,
                min(
                    dist_e.get(u, (10**9, "-")),
                    dist_d.get(u, (10**9, "-")),
                ),
                min(
                    dist_e.get(c, (10**9, "-")),
                    dist_d.get(c, (10**9, "-")),
                ),
                (
                    "E"
                    if dist_e.get(c, (10**9, "-"))
                    <= dist_d.get(c, (10**9, "-"))
                    else "D"
                ),
            )
            if u in dist_e or u in dist_d or c in dist_e or c in dist_d:
                hits.append(row)
            else:
                misses.append(row)
            if len(misses) >= args.examples:
                break
        if len(misses) >= args.examples:
            break

    print(f"checked high-return rows: {checked}")
    print(f"rows touching E/D descendant trees within depth {args.depth}: {len(hits)}")
    print(f"rows with neither u nor c found: {len(misses)}")
    print("columns: x r k v V E D u c dist(u) dist(c); 1e9 means absent")
    if args.show_hits:
        for row in hits[: args.examples]:
            print("HIT", *row)
    for row in misses[: args.examples]:
        print("MISS", *row)


if __name__ == "__main__":
    main()
