from pathlib import Path
import re


def patch_ledger() -> None:
    p = Path("docs/proof-ledger.md")
    text = p.read_text(encoding="utf-8")

    old136 = "| In a fixed outer source/proof-token fibre, the active normalizer has its own inner source/token ordinal; every high-return cross-transition is strict in that inner rank before a new marked pair is installed, D>=3 pays another token edge, and D=1,2 is pure routing to one exact lift, so a second application of the fibre lemma plus Sections 91--96 excludes infinite alternation | **PROVED FIXED-FIBRE NORMALIZER WELL-FOUNDEDNESS** | Section 136 of docs/verified-results.md |"
    new136 = "| For every provenance-preserving typed entry generated by Sections 91--135, the marked/obligation normalizer is well-founded in the retained source/token fibre; temporary A-growth is routing data and is not promoted to the retained anchor | **PROVED FOR TYPED ENTRIES** | Corrected Section 136 of docs/verified-results.md |"

    old137 = "| Every globally minimum-source DRAW normalizes through Sections 14--27 to a strict source/token edge or the generic A-selecting obligation; the separate height-one ordinary and resonant exceptional rows normalize through Sections 69--90 to the same three alternatives, so no upstream raw/factor entry lies outside the Section 136 normalizer | **PROVED GLOBAL ENTRY COMPLETENESS** | Section 137 of docs/verified-results.md |"
    new137 = "| Every arbitrary factorful exponent-one DRAW Q_1^epsilon(3^k J(s)), k>0, has the exact two-level raw/signed normalization of corrected Section 137; the returned source need not be below s | **PROVED ARITHMETIC NORMALIZATION** | Corrected Section 137, using universal Sections 79--81 |\n| The arbitrary factorful exponent-one normalization can always be attached to the old retained source/proof-token projection by a strict edge or a typed Section 136 entry | **OPEN — ARBITRARY EXPONENT-ONE ATTACHMENT LEMMA** | Corrected Section 137; this is the current global blocking lemma |"

    oldthm = "| Every starting value is `WIN` or `LOSS`, with no `DRAW`; equivalently optimal play reaches 1 in finite time from every odd start | **PROVED** | Sections 129--138 of docs/verified-results.md; concise assembly in docs/global-proof.md |"
    newthm = "| Every starting value is `WIN` or `LOSS`, with no `DRAW`; equivalently optimal play reaches 1 in finite time from every odd start | **OPEN IN THIS MANUSCRIPT** | Would follow from Sections 129, 132, 136 after the attachment lemma in corrected Section 137 is proved |"

    for old, new, label in [
        (old136, new136, "136"),
        (old137, new137, "137"),
        (oldthm, newthm, "theorem"),
    ]:
        if old not in text:
            raise RuntimeError(f"proof-ledger row {label} not found")
        text = text.replace(old, new, 1)

    p.write_text(text, encoding="utf-8")


def patch_paper() -> None:
    p = Path("paper/main.tex")
    text = p.read_text(encoding="utf-8")

    text = text.replace(
        r"\title{Termination under Optimal Play in the Two-Player $3n\mathbin{\pm}1$ Game}",
        r"\title{A Binary Normal Form and an Audited Proof Attempt for the Two-Player $3n\mathbin{\pm}1$ Game}",
        1,
    )
    text = text.replace(
        r"\date{Preprint, 8 August 2026}",
        r"\date{Audited repair draft, 9 August 2026}",
        1,
    )

    new_abstract = r"""\begin{abstract}
We consider the impartial two-player game on positive odd integers in which a
move replaces $n>1$ by the odd part of either $3n-1$ or $3n+1$, and the player
who reaches $1$ wins. Arbitrary play need not terminate. We give an exact
binary normal form with one expanding and one strictly contracting branch and
develop a large collection of source, factor, and finite proof-height
normalizations. An external audit by Ingo Alth\"ofer identified a genuine gap
in the previous global entry argument: a decrease of the canonical odd
coefficient was incorrectly used as a decrease of its coefficient source,
and an arbitrary factorful exponent-one family was not covered by the reverse
factor lemma. The corrected supplement proves a universal two-level arithmetic
normalization for that missing family using Sections 79--81, but the returned
source can increase. The remaining provenance/rank attachment lemma is stated
explicitly in corrected Section 137. Consequently the global no-draw theorem
is \emph{not claimed as proved in this repair draft}. The computational,
symbolic-certificate, and Lean artifacts remain supporting checks with the
narrow trust boundary stated in the repository.
\end{abstract}"""
    text, n = re.subn(
        r"\\begin\{abstract\}.*?\\end\{abstract\}",
        lambda _: new_abstract,
        text,
        count=1,
        flags=re.S,
    )
    if n != 1:
        raise RuntimeError("abstract block not found")

    new_target = r"""\paragraph{Target theorem (open).}\label{thm:main}
The target statement is that for every positive odd starting integer, optimal
play reaches $1$ after finitely many moves, equivalently that the game has no
$\DRAW$ positions. The external audit described above shows that the current
manuscript does not yet prove this statement. Corrected Section 137 of the
supplement isolates the remaining attachment lemma exactly."""
    text, n = re.subn(
        r"\\begin\{theorem\}\[Main theorem\]\\label\{thm:main\}.*?\\end\{theorem\}",
        lambda _: new_target,
        text,
        count=1,
        flags=re.S,
    )
    if n != 1:
        raise RuntimeError("main theorem block not found")

    new_fixed = r"""\begin{lemma}[Typed fixed-fibre normalizer; corrected Supplement Section 136]
Once a provenance-preserving typed entry has supplied the retained source
anchor and certified proof tokens required by Sections 91--135, the
corresponding marked obligation/factor routing is well-founded in that fixed
retained fibre.
\end{lemma}

\begin{proof}[Scope of the repaired statement]
The retained arithmetic anchor is not the temporary obligation cursor.
Canonical $A$-continuations may increase the cursor and are treated as bounded
routing macros; they do not update the retained numerical rank. Strict source
changes and finite proof-token replacements are admitted only where the cited
lemmas prove the corresponding comparison. Sections 93--135 then control the
bounded $A$-streaks, valuation-two witnesses, factor forks, and high-return
cross-transitions for these typed entries. The missing issue is upstream: an
arbitrary factorful exponent-one DRAW has not yet been proved to acquire such
an entry without increasing the retained projection.
\end{proof}"""
    text, n = re.subn(
        r"\\begin\{lemma\}\[Fixed-fibre normalizer; Supplement Section 136\].*?\\end\{proof\}",
        lambda _: new_fixed,
        text,
        count=1,
        flags=re.S,
    )
    if n != 1:
        raise RuntimeError("fixed-fibre lemma block not found")

    new_entry = r"""\section{Audited entry gap and corrected arithmetic normalization}

The previous version asserted an exhaustive entry trichotomy. That assertion
was too strong. At a constant-tail boundary, Section 15 proves a decrease of
the canonical odd coefficient, not necessarily a decrease of the coefficient
\emph{source}. For example, $s=1$, $J(1)=5$, $a=15$, and $\epsilon=1$
give the common child $R(44)=22$, whose canonical coefficient is $11<15$ but
whose source is $3>1$ because $11=J(3)$.

The omitted arithmetic family is
\[
 Q_1^\epsilon(3^kJ(s)),\qquad k>0.
\]
The reverse-factor lemma applies only at exponent at least two. Corrected
Supplement Section 137 instead applies the universal two-level factor scan of
Sections 79--81. If the displayed state is DRAW, a DRAW occurs among the raw
and signed exits at the current or next factor level. Writing
\[
 3^{i+1}J(s)+1-2\epsilon=2^vJ(t),
\]
the signed exit is exactly $Q_v^{1-\epsilon}(J(t))$; for $v\ge2$ its raw
sibling is $Q_{v-1}^{1-\epsilon}(J(t))$, and for $v=1$ a positive raw DRAW
has coefficient source strictly below $t$.

This repairs the arithmetic exhaustiveness defect but does not prove that
$t<s$. In general the returned source may be larger. The remaining statement
is therefore a provenance statement, not another arithmetic factorization.

\paragraph{Remaining attachment lemma.}
Let $s$ be the globally least coefficient source of a DRAW and suppose
$Q_1^\epsilon(3^kJ(s))$ is DRAW with $k>0$. Starting from the two-level
normalization above, one must prove that an outcome-compatible finite
continuation either reaches an actual DRAW with retained source below $s$,
performs a certified strict replacement of an already carried finite proof
token, or enters the typed Section 136 normalizer while preserving the old
retained source/token projection. A temporary returned source $t$ may be
routing data but may not silently replace the retained anchor $s$.

For $s>0$ the ordinary state $s$ itself is finite, since its own coefficient
source is at most $(s-1)/6<s$. Sections 54, 57, and 61--64 therefore provide
finite proof-tree provenance that may be used in a completion. The source-zero
case is normalized separately in Sections 71--73.

\section{Current theorem status}

Because the attachment lemma above is still open, the no-$\DRAW$ theorem is
open in this manuscript. Sections 129 and 132 remain valid order-theoretic
lemmas, and corrected Section 136 remains valid for typed entries. If the
attachment lemma is proved, the previous final well-foundedness assembly can
be reinstated: strict retained-source and proof-token transitions cannot occur
infinitely, and an equal retained-rank path is trapped in the typed
well-founded normalizer. Until then, no such global conclusion is asserted.

"""
    text, n = re.subn(
        r"\\section\{Entry completeness\}.*?(?=\\section\{Verification status and reproducibility\})",
        lambda _: new_entry,
        text,
        count=1,
        flags=re.S,
    )
    if n != 1:
        raise RuntimeError("entry/exclusion block not found")

    old_certificate = (
        "Thus acceptance of the JSON certificate validates the final size-change\n"
        "assembly conditional on the cited Sections 14--137; it is not presented as a\n"
        "complete machine proof from the original move relation."
    )
    new_certificate = (
        "Thus acceptance of the JSON certificate validates only the declared typed\n"
        "size-change assembly. Corrected Section 137 leaves one semantic attachment\n"
        "obligation open, so certificate acceptance is not evidence for the global\n"
        "no-$\\DRAW$ theorem."
    )
    if old_certificate not in text:
        raise RuntimeError("certificate status paragraph not found")
    text = text.replace(old_certificate, new_certificate, 1)

    new_conclusion = r"""\section{Conclusion}

The binary normal form and the local factor/source identities survive the
external audit. The audit nevertheless invalidates the previous global proof:
the arbitrary factorful exponent-one family was not attached to the retained
well-founded rank. The corrected supplement now gives a complete two-level
arithmetic normalization of that family and isolates the remaining
provenance/rank attachment lemma. The global termination statement remains
open until that lemma is proved and independently re-audited.

"""
    text, n = re.subn(
        r"\\section\{Conclusion\}.*?(?=\\section\*\{Data, code, and correspondence\})",
        lambda _: new_conclusion,
        text,
        count=1,
        flags=re.S,
    )
    if n != 1:
        raise RuntimeError("conclusion block not found")

    p.write_text(text, encoding="utf-8")


def main() -> None:
    patch_ledger()
    patch_paper()

    ledger = Path("docs/proof-ledger.md").read_text(encoding="utf-8")
    paper = Path("paper/main.tex").read_text(encoding="utf-8")
    assert "OPEN — ARBITRARY EXPONENT-ONE ATTACHMENT LEMMA" in ledger
    assert "PROVED GLOBAL ENTRY COMPLETENESS" not in ledger
    assert "Target theorem (open)" in paper
    assert "Remaining attachment lemma" in paper


if __name__ == "__main__":
    main()
